import type { BblGalaxyGraph } from "./bbl-galaxy-types"

const legendIds = [
  "bob-bass",
  "chris-haueter",
  "erik-paulson",
  "john-will",
  "dave-meyer",
  "rick-williams",
  "casey-olson",
]

export const bblGalaxyMockGraph: BblGalaxyGraph = {
  groups: [
    {
      id: "machado-lineage",
      label: "Machado Lineage",
      kind: "LINEAGE_BRANCH",
      generation: 0,
      color: "#f5d27a",
    },
    {
      id: "dirty-dozen",
      label: "Dirty Dozen Constellation",
      kind: "PROMOTION_COHORT",
      generation: 1,
      color: "#d9a441",
    },
    {
      id: "american-bjj",
      label: "American Jiu-Jitsu Expansion",
      kind: "TIMELINE_BAND",
      generation: 2,
      color: "#7fd7ff",
    },
  ],

  nodes: [
    {
      id: "rigan-machado",
      displayName: "Rigan Machado",
      initials: "RM",
      slug: "rigan-machado",
      role: "ROOT_STAR",
      discipline: "BJJ",
      rankLabel: "Red Belt",
      title: "Lineage Anchor",
      verifiedStatus: "VERIFIED",
      generation: 0,
      orbitIndex: 0,
      orbitTotal: 1,
      groupId: "machado-lineage",
      groupLabel: "Machado Lineage",
      timelineYear: 2026,
    },
    {
      id: "bob-bass",
      displayName: "Bob Bass",
      initials: "BB",
      slug: "bob-bass",
      role: "LEGEND_STAR",
      discipline: "BJJ",
      rankLabel: "Coral Belt",
      title: "American Pioneer",
      verifiedStatus: "VERIFIED",
      generation: 1,
      orbitIndex: 0,
      orbitTotal: 12,
      groupId: "dirty-dozen",
      groupLabel: "Dirty Dozen",
      timelineYear: 1990,
    },
    {
      id: "chris-haueter",
      displayName: "Chris Haueter",
      initials: "CH",
      slug: "chris-haueter",
      role: "LEGEND_STAR",
      discipline: "BJJ",
      rankLabel: "Coral Belt",
      title: "Combat Base Pioneer",
      verifiedStatus: "VERIFIED",
      generation: 1,
      orbitIndex: 1,
      orbitTotal: 12,
      groupId: "dirty-dozen",
      groupLabel: "Dirty Dozen",
      timelineYear: 1990,
    },
    {
      id: "erik-paulson",
      displayName: "Erik Paulson",
      initials: "EP",
      slug: "erik-paulson",
      role: "LEGEND_STAR",
      discipline: "BJJ",
      rankLabel: "Coral Belt",
      title: "CSW / MMA Bridge",
      verifiedStatus: "VERIFIED",
      generation: 1,
      orbitIndex: 2,
      orbitTotal: 12,
      groupId: "dirty-dozen",
      groupLabel: "Dirty Dozen",
      timelineYear: 1990,
    },
    {
      id: "john-will",
      displayName: "John Will",
      initials: "JW",
      slug: "john-will",
      role: "LEGEND_STAR",
      discipline: "BJJ",
      rankLabel: "Coral Belt",
      title: "Global Expansion",
      verifiedStatus: "VERIFIED",
      generation: 1,
      orbitIndex: 3,
      orbitTotal: 12,
      groupId: "dirty-dozen",
      groupLabel: "Dirty Dozen",
      timelineYear: 1990,
    },
    {
      id: "dave-meyer",
      displayName: "Dave Meyer",
      initials: "DM",
      slug: "dave-meyer",
      role: "LEGEND_STAR",
      discipline: "BJJ",
      rankLabel: "Black Belt",
      title: "Legacy Historian",
      verifiedStatus: "VERIFIED",
      generation: 1,
      orbitIndex: 4,
      orbitTotal: 12,
      groupId: "dirty-dozen",
      groupLabel: "Dirty Dozen",
      timelineYear: 1990,
    },
    {
      id: "rick-williams",
      displayName: "Rick Williams",
      initials: "RW",
      slug: "rick-williams",
      role: "LEGEND_STAR",
      discipline: "BJJ",
      rankLabel: "Black Belt",
      title: "American Pioneer",
      verifiedStatus: "VERIFIED",
      generation: 1,
      orbitIndex: 5,
      orbitTotal: 12,
      groupId: "dirty-dozen",
      groupLabel: "Dirty Dozen",
      timelineYear: 1990,
    },
    {
      id: "casey-olson",
      displayName: "Casey Olson",
      initials: "CO",
      slug: "casey-olson",
      role: "LEGEND_STAR",
      discipline: "BJJ",
      rankLabel: "Black Belt",
      title: "American Pioneer",
      verifiedStatus: "VERIFIED",
      generation: 1,
      orbitIndex: 6,
      orbitTotal: 12,
      groupId: "dirty-dozen",
      groupLabel: "Dirty Dozen",
      timelineYear: 1990,
    },
    ...Array.from({ length: 24 }).map((_, index) => ({
      id: `instructor-${index + 1}`,
      displayName: `Legacy Instructor ${index + 1}`,
      initials: `L${index + 1}`,
      slug: `legacy-instructor-${index + 1}`,
      role: "INSTRUCTOR_PLANET" as const,
      discipline: "BJJ" as const,
      rankLabel: "Black Belt",
      title: "Instructor",
      verifiedStatus: "VERIFIED" as const,
      generation: 2,
      orbitIndex: index,
      orbitTotal: 24,
      groupId: "american-bjj",
      groupLabel: "American Jiu-Jitsu Expansion",
      timelineYear: 2000 + (index % 12),
    })),
    ...Array.from({ length: 18 }).map((_, index) => ({
      id: `student-${index + 1}`,
      displayName: `Legacy Student ${index + 1}`,
      initials: `S${index + 1}`,
      slug: `legacy-student-${index + 1}`,
      role: "STUDENT_MOON" as const,
      discipline: "BJJ" as const,
      rankLabel: "Student",
      title: "Lineage Student",
      verifiedStatus: "VERIFIED" as const,
      generation: 3,
      orbitIndex: index,
      orbitTotal: 18,
      groupId: "american-bjj",
      groupLabel: "American Jiu-Jitsu Expansion",
      timelineYear: 2010 + (index % 10),
    })),
  ],

  edges: [
    ...legendIds.map((legendId) => ({
      id: `rigan-to-${legendId}`,
      sourceId: "rigan-machado",
      targetId: legendId,
      relationshipType: "PRIMARY_LINEAGE" as const,
      verifiedStatus: "VERIFIED" as const,
      groupId: "dirty-dozen",
    })),
    ...Array.from({ length: 24 }).map((_, index) => ({
      id: `legend-to-instructor-${index + 1}`,
      sourceId: legendIds[index % legendIds.length],
      targetId: `instructor-${index + 1}`,
      relationshipType: "PRIMARY_LINEAGE" as const,
      verifiedStatus: "VERIFIED" as const,
      groupId: "american-bjj",
    })),
    ...Array.from({ length: 18 }).map((_, index) => ({
      id: `instructor-to-student-${index + 1}`,
      sourceId: `instructor-${(index % 12) + 1}`,
      targetId: `student-${index + 1}`,
      relationshipType: "PRIMARY_LINEAGE" as const,
      verifiedStatus: "VERIFIED" as const,
      groupId: "american-bjj",
    })),
  ],
}
